// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartLock.DBApi.Data;

#nullable disable

namespace SmartLockDBAPI.Migrations
{
    [DbContext(typeof(SmartLockDbContext))]
    [Migration("20260317225418_Add_AutoLock_EventType")]
    partial class Add_AutoLock_EventType
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.Device", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<byte[]>("DeviceSecret")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("DeviceId");

                    b.ToTable("Devices");
                });

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.DeviceSetting", b =>
                {
                    b.Property<Guid>("DeviceSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SettingId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DeviceSettingId");

                    b.HasIndex("SettingId");

                    b.HasIndex("DeviceId", "SettingId")
                        .IsUnique();

                    b.ToTable("DeviceSettings");
                });

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.Event", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EventTypeId")
                        .HasColumnType("int");

                    b.Property<Guid?>("KeyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EventId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("KeyId");

                    b.HasIndex("DeviceId", "EventTypeId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.EventType", b =>
                {
                    b.Property<int>("EventTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventTypeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EventTypeId");

                    b.ToTable("EventTypes");

                    b.HasData(
                        new
                        {
                            EventTypeId = 1,
                            Name = "ButtonLock"
                        },
                        new
                        {
                            EventTypeId = 2,
                            Name = "RemoteLock"
                        },
                        new
                        {
                            EventTypeId = 3,
                            Name = "AutoLock"
                        },
                        new
                        {
                            EventTypeId = 4,
                            Name = "SuccessKeyUnlock"
                        },
                        new
                        {
                            EventTypeId = 5,
                            Name = "FailKeyUnlock"
                        },
                        new
                        {
                            EventTypeId = 6,
                            Name = "ButtonUnlock"
                        },
                        new
                        {
                            EventTypeId = 7,
                            Name = "RemoteUnlock"
                        },
                        new
                        {
                            EventTypeId = 8,
                            Name = "Open"
                        },
                        new
                        {
                            EventTypeId = 9,
                            Name = "Close"
                        });
                });

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.RfidKeyEntry", b =>
                {
                    b.Property<Guid>("KeyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsValid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("LastUsed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TagUid")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("KeyId");

                    b.HasIndex("TagUid")
                        .IsUnique();

                    b.ToTable("Keys");
                });

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.Setting", b =>
                {
                    b.Property<int>("SettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SettingId"));

                    b.Property<string>("DefaultValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("SettingId");

                    b.ToTable("Settings");

                    b.HasData(
                        new
                        {
                            SettingId = 1,
                            DefaultValue = "1",
                            Name = "AutoLockEnabled"
                        },
                        new
                        {
                            SettingId = 2,
                            DefaultValue = "15",
                            Name = "AutoLockDelaySec"
                        },
                        new
                        {
                            SettingId = 3,
                            DefaultValue = "1",
                            Name = "DoorOpenBuzzEnabled"
                        },
                        new
                        {
                            SettingId = 4,
                            DefaultValue = "60",
                            Name = "DoorOpenBuzzDelaySec"
                        },
                        new
                        {
                            SettingId = 5,
                            DefaultValue = "1",
                            Name = "OpenCloseToneId"
                        });
                });

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.DeviceSetting", b =>
                {
                    b.HasOne("SmartLock.DBApi.DataAccess.Device", "Device")
                        .WithMany("DeviceSettings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SmartLock.DBApi.DataAccess.Setting", "Setting")
                        .WithMany("DeviceSettings")
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Setting");
                });

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.Event", b =>
                {
                    b.HasOne("SmartLock.DBApi.DataAccess.Device", "Device")
                        .WithMany("Events")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SmartLock.DBApi.DataAccess.EventType", "EventType")
                        .WithMany("Events")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartLock.DBApi.DataAccess.RfidKeyEntry", "Key")
                        .WithMany("Events")
                        .HasForeignKey("KeyId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Device");

                    b.Navigation("EventType");

                    b.Navigation("Key");
                });

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.Device", b =>
                {
                    b.Navigation("DeviceSettings");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.EventType", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.RfidKeyEntry", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("SmartLock.DBApi.DataAccess.Setting", b =>
                {
                    b.Navigation("DeviceSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
